name: Build and Deploy to GitHub Pages (Main branch root)

on:
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build with Vite
        run: npx vite build

      - name: Clean old site files except workflow and config files
        run: |
          find . -maxdepth 1 \
            ! -name '.' \
            ! -name 'dist' \
            ! -name '.github' \
            ! -name '.git' \
            ! -name '.gitignore' \
            ! -name 'package.json' \
            ! -name 'package-lock.json' \
            ! -name 'README.md' \
            -exec rm -rf {} +

      - name: Copy dist files to repo root
        run: cp -a dist/. .

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/sudo-self/sudo-self.github.io.git
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Deploy updated site [skip ci]"
            git push origin main
          fi


