name: Build and Deploy to GitHub Pages (Main branch root)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build site with Vite
        run: npm run build

      - name: Confirm dist folder exists
        run: |
          if [ ! -d "dist" ]; then
            echo "❌ dist folder not found after build. Exiting."
            exit 1
          fi

      - name: Clean old files (except key files)
        run: |
          find . -maxdepth 1 \
            ! -name '.' \
            ! -name 'dist' \
            ! -name '.github' \
            ! -name '.git' \
            ! -name '.gitignore' \
            ! -name 'package.json' \
            ! -name 'package-lock.json' \
            ! -name 'README.md' \
            ! -name 'CNAME' \
            -exec rm -rf {} +

      - name: Copy build files to root
        run: cp -a dist/. .

      - name: Commit and Push to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add -A

          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "🚀 Deploy updated site [skip ci]"
            git push origin main || (echo "❌ Push failed" && exit 1)
          fi



